#!/usr/bin/python
# Usage: typeslots.py < Include/typeslots.h typeslots.inc

agiza sys, re

eleza generate_typeslots(out=sys.stdout):
    out.write("/* Generated by typeslots.py */\n")
    res = {}
    kila line kwenye sys.stdin:
        m = re.match("#define Py_([a-z_]+) ([0-9]+)", line)
        ikiwa sio m:
            endelea
        member = m.group(1)
        ikiwa member.startswith("tp_"):
            member = "ht_type."+member
        lasivyo member.startswith("am_"):
            member = "as_async."+member
        lasivyo member.startswith("nb_"):
            member = "as_number."+member
        lasivyo member.startswith("mp_"):
            member = "as_mapping."+member
        lasivyo member.startswith("sq_"):
            member = "as_sequence."+member
        lasivyo member.startswith("bf_"):
            member = "as_buffer."+member
        res[int(m.group(2))] = member

    M = max(res.keys())+1
    kila i kwenye range(1,M):
        ikiwa i kwenye res:
            out.write("offsetof(PyHeapTypeObject, %s),\n" % res[i])
        isipokua:
            out.write("0,\n")

eleza main():
    ikiwa len(sys.argv) == 2:
        ukijumuisha open(sys.argv[1], "w") kama f:
            generate_typeslots(f)
    isipokua:
        generate_typeslots()

ikiwa __name__ == "__main__":
    main()
