agiza sys, os

# Template used then the program ni a GUI program
WINMAINTEMPLATE = """
#include <windows.h>

int WINAPI WinMain(
    HINSTANCE hInstance,      // handle to current instance
    HINSTANCE hPrevInstance,  // handle to previous instance
    LPSTR lpCmdLine,          // pointer to command line
    int nCmdShow              // show state of window
    )
{
    extern int Py_FrozenMain(int, char **);
    PyImport_FrozenModules = _PyImport_FrozenModules;
    rudisha Py_FrozenMain(__argc, __argv);
}
"""

SERVICETEMPLATE = """
extern int PythonService_main(int, char **);

int main( int argc, char **argv)
{
    PyImport_FrozenModules = _PyImport_FrozenModules;
    rudisha PythonService_main(argc, argv);
}
"""

subsystem_details = {
    # -s flag        : (C entry point template), (is it __main__?), (is it a DLL?)
    'console'        : (Tupu,                    1,                 0),
    'windows'        : (WINMAINTEMPLATE,         1,                 0),
    'service'        : (SERVICETEMPLATE,         0,                 0),
    'com_dll'        : ("",                      0,                 1),
}

eleza get_custom_entry_point(subsystem):
    jaribu:
        rudisha subsystem_details[subsystem][:2]
    tatizo KeyError:
        ashiria ValueError("The subsystem %s ni sio known" % subsystem) kutoka Tupu


eleza makemakefile(outfp, vars, files, target):
    save = sys.stdout
    jaribu:
        sys.stdout = outfp
        realwork(vars, files, target)
    mwishowe:
        sys.stdout = save

eleza realwork(vars, moddefns, target):
    version_suffix = "%r%r" % sys.version_info[:2]
    andika("# Makefile kila Microsoft Visual C++ generated by freeze.py script")
    andika()
    andika('target = %s' % target)
    andika('pythonhome = %s' % vars['prefix'])
    andika()
    andika('DEBUG=0 # Set to 1 to use the _d versions of Python.')
    andika('!IF $(DEBUG)')
    andika('debug_suffix=_d')
    andika('c_debug=/Zi /Od /DDEBUG /D_DEBUG')
    andika('l_debug=/DEBUG')
    andika('temp_dir=Build\\Debug')
    andika('!ELSE')
    andika('debug_suffix=')
    andika('c_debug=/Ox')
    andika('l_debug=')
    andika('temp_dir=Build\\Release')
    andika('!ENDIF')
    andika()

    andika('# The following line assumes you have built Python using the standard instructions')
    andika('# Otherwise fix the following line to point to the library.')
    andika('pythonlib = "$(pythonhome)/pcbuild/python%s$(debug_suffix).lib"' % version_suffix)
    andika()

    # We only ever write one "entry point" symbol - either
    # "main" ama "WinMain".  Therefore, there ni no need to
    # pita a subsystem switch to the linker kama it works it
    # out all by itself.  However, the subsystem _does_ determine
    # the file extension na additional linker flags.
    target_link_flags = ""
    target_ext = ".exe"
    ikiwa subsystem_details[vars['subsystem']][2]:
        target_link_flags = "-dll"
        target_ext = ".dll"


    andika("# As the target uses Python%s.dll, we must use this compiler option!" % version_suffix)
    andika("cdl = /MD")
    andika()
    andika("all: $(target)$(debug_suffix)%s" % (target_ext))
    andika()

    andika('$(temp_dir):')
    andika(r'  ikiwa sio exist $(temp_dir)\. mkdir $(temp_dir)')
    andika()

    objects = []
    libs = ["shell32.lib", "comdlg32.lib", "wsock32.lib", "user32.lib", "oleaut32.lib"]
    kila moddefn kwenye moddefns:
        andika("# Module", moddefn.name)
        kila file kwenye moddefn.sourceFiles:
            base = os.path.basename(file)
            base, ext = os.path.splitext(base)
            objects.append(base + ".obj")
            andika(r'$(temp_dir)\%s.obj: "%s"' % (base, file))
            andika("\t@$(CC) -c -nologo /Fo$* $(cdl) $(c_debug) /D BUILD_FREEZE", end=' ')
            andika('"-I$(pythonhome)/Include"  "-I$(pythonhome)/PC" \\')
            andika("\t\t$(cflags) $(cdebug) $(cinclude) \\")
            extra = moddefn.GetCompilerOptions()
            ikiwa extra:
                andika("\t\t%s \\" % (' '.join(extra),))
            andika('\t\t"%s"' % file)
            andika()

        # Add .lib files this module needs
        kila modlib kwenye moddefn.GetLinkerLibs():
            ikiwa modlib haiko kwenye libs:
                libs.append(modlib)

    andika("ADDN_LINK_FILES=", end=' ')
    kila addn kwenye vars['addn_link']: andika('"%s"' % (addn), end=' ')
    andika() ; andika()

    andika("OBJS=", end=' ')
    kila obj kwenye objects: andika(r'"$(temp_dir)\%s"' % (obj), end=' ')
    andika() ; andika()

    andika("LIBS=", end=' ')
    kila lib kwenye libs: andika('"%s"' % (lib), end=' ')
    andika() ; andika()

    andika("$(target)$(debug_suffix)%s: $(temp_dir) $(OBJS)" % (target_ext))
    andika("\tlink -out:$(target)$(debug_suffix)%s %s" %
          (target_ext, target_link_flags), "@<<")
    andika("\t$(OBJS)")
    andika("\t$(LIBS)")
    andika("\t$(ADDN_LINK_FILES)")
    andika("\t$(pythonlib) $(lcustom) $(l_debug)")
    andika("\t$(resources)")
    andika("<<")
    andika()
    andika("clean:")
    andika("\t-toa /f *.obj")
    andika("\t-toa /f $(target).exe")
