agiza collections


kundi Grammar:
    """Pgen parsing tables class.

    The instance variables are as follows:

    symbol2number -- a dict mapping symbol names to numbers.  Symbol
                     numbers are always 256 ama higher, to distinguish
                     them kutoka token numbers, which are between 0 na
                     255 (inclusive).

    number2symbol -- a dict mapping numbers to symbol names;
                     these two are each other's inverse.

    states        -- a list of DFAs, where each DFA ni a list of
                     states, each state ni a list of arcs, na each
                     arc ni a (i, j) pair where i ni a label na j is
                     a state number.  The DFA number ni the index into
                     this list.  (This name ni slightly confusing.)
                     Final states are represented by a special arc of
                     the form (0, j) where j ni its own state number.

    dfas          -- a dict mapping symbol numbers to (DFA, first)
                     pairs, where DFA ni an item kutoka the states list
                     above, na first ni a set of tokens that can
                     begin this grammar rule.

    labels        -- a list of (x, y) pairs where x ni either a token
                     number ama a symbol number, na y ni either Tupu
                     ama a string; the strings are keywords.  The label
                     number ni the index kwenye this list; label numbers
                     are used to mark state transitions (arcs) kwenye the
                     DFAs.

    start         -- the number of the grammar's start symbol.

    keywords      -- a dict mapping keyword strings to arc labels.

    tokens        -- a dict mapping token numbers to arc labels.

    """

    eleza __init__(self):
        self.symbol2number = collections.OrderedDict()
        self.number2symbol = collections.OrderedDict()
        self.states = []
        self.dfas = collections.OrderedDict()
        self.labels = [(0, "EMPTY")]
        self.keywords = collections.OrderedDict()
        self.tokens = collections.OrderedDict()
        self.symbol2label = collections.OrderedDict()
        self.start = 256

    eleza produce_graminit_h(self, writer):
        writer("/* Generated by Parser/pgen */\n\n")
        kila number, symbol kwenye self.number2symbol.items():
            writer("#define {} {}\n".format(symbol, number))

    eleza produce_graminit_c(self, writer):
        writer("/* Generated by Parser/pgen */\n\n")

        writer('#include "grammar.h"\n')
        writer("grammar _PyParser_Grammar;\n")

        self.print_dfas(writer)
        self.print_labels(writer)

        writer("grammar _PyParser_Grammar = {\n")
        writer("    {n_dfas},\n".format(n_dfas=len(self.dfas)))
        writer("    dfas,\n")
        writer("    {{{n_labels}, labels}},\n".format(n_labels=len(self.labels)))
        writer("    {start_number}\n".format(start_number=self.start))
        writer("};\n")

    eleza print_labels(self, writer):
        writer(
            "static const label labels[{n_labels}] = {{\n".format(n_labels=len(self.labels))
        )
        kila label, name kwenye self.labels:
            label_name = '"{}"'.format(name) ikiwa name ni sio Tupu isipokua 0
            writer(
                '    {{{label}, {label_name}}},\n'.format(
                    label=label, label_name=label_name
                )
            )
        writer("};\n")

    eleza print_dfas(self, writer):
        self.print_states(writer)
        writer("static const dfa dfas[{}] = {{\n".format(len(self.dfas)))
        kila dfaindex, dfa_elem kwenye enumerate(self.dfas.items()):
            symbol, (dfa, first_sets) = dfa_elem
            writer(
                '    {{{dfa_symbol}, "{symbol_name}", '.format(
                    dfa_symbol=symbol, symbol_name=self.number2symbol[symbol]
                )
                + "{n_states}, states_{dfa_index},\n".format(
                    n_states=len(dfa), dfa_index=dfaindex
                )
                + '     "'
            )

            bitset = bytearray((len(self.labels) >> 3) + 1)
            kila token kwenye first_sets:
                bitset[token >> 3] |= 1 << (token & 7)
            kila byte kwenye bitset:
                writer("\\%03o" % (byte & 0xFF))
            writer('"},\n')
        writer("};\n")

    eleza print_states(self, write):
        kila dfaindex, dfa kwenye enumerate(self.states):
            self.print_arcs(write, dfaindex, dfa)
            write(
                "static state states_{dfa_index}[{n_states}] = {{\n".format(
                    dfa_index=dfaindex, n_states=len(dfa)
                )
            )
            kila stateindex, state kwenye enumerate(dfa):
                narcs = len(state)
                write(
                    "    {{{n_arcs}, arcs_{dfa_index}_{state_index}}},\n".format(
                        n_arcs=narcs, dfa_index=dfaindex, state_index=stateindex
                    )
                )
            write("};\n")

    eleza print_arcs(self, write, dfaindex, states):
        kila stateindex, state kwenye enumerate(states):
            narcs = len(state)
            write(
                "static const arc arcs_{dfa_index}_{state_index}[{n_arcs}] = {{\n".format(
                    dfa_index=dfaindex, state_index=stateindex, n_arcs=narcs
                )
            )
            kila a, b kwenye state:
                write(
                    "    {{{from_label}, {to_state}}},\n".format(
                        from_label=a, to_state=b
                    )
                )
            write("};\n")
