/* Generated by Parser/pgen */

#include "grammar.h"
grammar _PyParser_Grammar;
static const arc arcs_0_0[3] = {
    {2, 1},
    {3, 2},
    {4, 1},
};
static const arc arcs_0_1[1] = {
    {0, 1},
};
static const arc arcs_0_2[1] = {
    {2, 1},
};
static state states_0[3] = {
    {3, arcs_0_0},
    {1, arcs_0_1},
    {1, arcs_0_2},
};
static const arc arcs_1_0[3] = {
    {64, 1},
    {2, 0},
    {65, 0},
};
static const arc arcs_1_1[1] = {
    {0, 1},
};
static state states_1[2] = {
    {3, arcs_1_0},
    {1, arcs_1_1},
};
static const arc arcs_2_0[1] = {
    {67, 1},
};
static const arc arcs_2_1[2] = {
    {64, 2},
    {2, 1},
};
static const arc arcs_2_2[1] = {
    {0, 2},
};
static state states_2[3] = {
    {1, arcs_2_0},
    {2, arcs_2_1},
    {1, arcs_2_2},
};
static const arc arcs_3_0[1] = {
    {10, 1},
};
static const arc arcs_3_1[1] = {
    {69, 2},
};
static const arc arcs_3_2[2] = {
    {5, 3},
    {2, 4},
};
static const arc arcs_3_3[2] = {
    {70, 5},
    {71, 6},
};
static const arc arcs_3_4[1] = {
    {0, 4},
};
static const arc arcs_3_5[1] = {
    {2, 4},
};
static const arc arcs_3_6[1] = {
    {70, 5},
};
static state states_3[7] = {
    {1, arcs_3_0},
    {1, arcs_3_1},
    {2, arcs_3_2},
    {2, arcs_3_3},
    {1, arcs_3_4},
    {1, arcs_3_5},
    {1, arcs_3_6},
};
static const arc arcs_4_0[1] = {
    {68, 1},
};
static const arc arcs_4_1[2] = {
    {68, 1},
    {0, 1},
};
static state states_4[2] = {
    {1, arcs_4_0},
    {2, arcs_4_1},
};
static const arc arcs_5_0[1] = {
    {72, 1},
};
static const arc arcs_5_1[3] = {
    {74, 2},
    {75, 2},
    {76, 2},
};
static const arc arcs_5_2[1] = {
    {0, 2},
};
static state states_5[3] = {
    {1, arcs_5_0},
    {3, arcs_5_1},
    {1, arcs_5_2},
};
static const arc arcs_6_0[1] = {
    {58, 1},
};
static const arc arcs_6_1[1] = {
    {76, 2},
};
static const arc arcs_6_2[1] = {
    {0, 2},
};
static state states_6[3] = {
    {1, arcs_6_0},
    {1, arcs_6_1},
    {1, arcs_6_2},
};
static const arc arcs_7_0[2] = {
    {24, 1},
    {26, 1},
};
static const arc arcs_7_1[1] = {
    {60, 2},
};
static const arc arcs_7_2[1] = {
    {77, 3},
};
static const arc arcs_7_3[2] = {
    {78, 4},
    {79, 5},
};
static const arc arcs_7_4[1] = {
    {80, 6},
};
static const arc arcs_7_5[2] = {
    {81, 7},
    {82, 8},
};
static const arc arcs_7_6[1] = {
    {79, 5},
};
static const arc arcs_7_7[1] = {
    {82, 8},
};
static const arc arcs_7_8[1] = {
    {0, 8},
};
static state states_7[9] = {
    {2, arcs_7_0},
    {1, arcs_7_1},
    {1, arcs_7_2},
    {2, arcs_7_3},
    {1, arcs_7_4},
    {2, arcs_7_5},
    {1, arcs_7_6},
    {1, arcs_7_7},
    {1, arcs_7_8},
};
static const arc arcs_8_0[1] = {
    {5, 1},
};
static const arc arcs_8_1[2] = {
    {70, 2},
    {83, 3},
};
static const arc arcs_8_2[1] = {
    {0, 2},
};
static const arc arcs_8_3[1] = {
    {70, 2},
};
static state states_8[4] = {
    {1, arcs_8_0},
    {2, arcs_8_1},
    {1, arcs_8_2},
    {1, arcs_8_3},
};
static const arc arcs_9_0[3] = {
    {6, 1},
    {84, 2},
    {85, 3},
};
static const arc arcs_9_1[4] = {
    {86, 4},
    {81, 5},
    {85, 6},
    {0, 1},
};
static const arc arcs_9_2[1] = {
    {85, 7},
};
static const arc arcs_9_3[4] = {
    {86, 8},
    {87, 9},
    {81, 5},
    {0, 3},
};
static const arc arcs_9_4[4] = {
    {84, 2},
    {81, 10},
    {85, 11},
    {0, 4},
};
static const arc arcs_9_5[1] = {
    {0, 5},
};
static const arc arcs_9_6[3] = {
    {86, 4},
    {81, 5},
    {0, 6},
};
static const arc arcs_9_7[3] = {
    {86, 12},
    {81, 5},
    {0, 7},
};
static const arc arcs_9_8[6] = {
    {6, 13},
    {84, 2},
    {88, 14},
    {81, 15},
    {85, 3},
    {0, 8},
};
static const arc arcs_9_9[1] = {
    {80, 16},
};
static const arc arcs_9_10[3] = {
    {84, 2},
    {85, 11},
    {0, 10},
};
static const arc arcs_9_11[4] = {
    {86, 4},
    {87, 17},
    {81, 5},
    {0, 11},
};
static const arc arcs_9_12[2] = {
    {81, 5},
    {0, 12},
};
static const arc arcs_9_13[4] = {
    {86, 18},
    {81, 5},
    {85, 19},
    {0, 13},
};
static const arc arcs_9_14[2] = {
    {86, 20},
    {0, 14},
};
static const arc arcs_9_15[5] = {
    {6, 13},
    {84, 2},
    {88, 14},
    {85, 3},
    {0, 15},
};
static const arc arcs_9_16[3] = {
    {86, 8},
    {81, 5},
    {0, 16},
};
static const arc arcs_9_17[1] = {
    {80, 6},
};
static const arc arcs_9_18[4] = {
    {84, 2},
    {81, 21},
    {85, 22},
    {0, 18},
};
static const arc arcs_9_19[3] = {
    {86, 18},
    {81, 5},
    {0, 19},
};
static const arc arcs_9_20[5] = {
    {6, 23},
    {84, 2},
    {81, 24},
    {85, 25},
    {0, 20},
};
static const arc arcs_9_21[3] = {
    {84, 2},
    {85, 22},
    {0, 21},
};
static const arc arcs_9_22[4] = {
    {86, 18},
    {87, 26},
    {81, 5},
    {0, 22},
};
static const arc arcs_9_23[4] = {
    {86, 27},
    {81, 5},
    {85, 28},
    {0, 23},
};
static const arc arcs_9_24[1] = {
    {85, 25},
};
static const arc arcs_9_25[4] = {
    {86, 29},
    {87, 30},
    {81, 5},
    {0, 25},
};
static const arc arcs_9_26[1] = {
    {80, 19},
};
static const arc arcs_9_27[4] = {
    {84, 2},
    {81, 31},
    {85, 32},
    {0, 27},
};
static const arc arcs_9_28[3] = {
    {86, 27},
    {81, 5},
    {0, 28},
};
static const arc arcs_9_29[5] = {
    {6, 33},
    {84, 2},
    {81, 34},
    {85, 25},
    {0, 29},
};
static const arc arcs_9_30[1] = {
    {80, 35},
};
static const arc arcs_9_31[3] = {
    {84, 2},
    {85, 32},
    {0, 31},
};
static const arc arcs_9_32[4] = {
    {86, 27},
    {87, 36},
    {81, 5},
    {0, 32},
};
static const arc arcs_9_33[4] = {
    {86, 37},
    {81, 5},
    {85, 38},
    {0, 33},
};
static const arc arcs_9_34[4] = {
    {6, 33},
    {84, 2},
    {85, 25},
    {0, 34},
};
static const arc arcs_9_35[3] = {
    {86, 29},
    {81, 5},
    {0, 35},
};
static const arc arcs_9_36[1] = {
    {80, 28},
};
static const arc arcs_9_37[4] = {
    {84, 2},
    {81, 39},
    {85, 40},
    {0, 37},
};
static const arc arcs_9_38[3] = {
    {86, 37},
    {81, 5},
    {0, 38},
};
static const arc arcs_9_39[3] = {
    {84, 2},
    {85, 40},
    {0, 39},
};
static const arc arcs_9_40[4] = {
    {86, 37},
    {87, 41},
    {81, 5},
    {0, 40},
};
static const arc arcs_9_41[1] = {
    {80, 38},
};
static state states_9[42] = {
    {3, arcs_9_0},
    {4, arcs_9_1},
    {1, arcs_9_2},
    {4, arcs_9_3},
    {4, arcs_9_4},
    {1, arcs_9_5},
    {3, arcs_9_6},
    {3, arcs_9_7},
    {6, arcs_9_8},
    {1, arcs_9_9},
    {3, arcs_9_10},
    {4, arcs_9_11},
    {2, arcs_9_12},
    {4, arcs_9_13},
    {2, arcs_9_14},
    {5, arcs_9_15},
    {3, arcs_9_16},
    {1, arcs_9_17},
    {4, arcs_9_18},
    {3, arcs_9_19},
    {5, arcs_9_20},
    {3, arcs_9_21},
    {4, arcs_9_22},
    {4, arcs_9_23},
    {1, arcs_9_24},
    {4, arcs_9_25},
    {1, arcs_9_26},
    {4, arcs_9_27},
    {3, arcs_9_28},
    {5, arcs_9_29},
    {1, arcs_9_30},
    {3, arcs_9_31},
    {4, arcs_9_32},
    {4, arcs_9_33},
    {4, arcs_9_34},
    {3, arcs_9_35},
    {1, arcs_9_36},
    {4, arcs_9_37},
    {3, arcs_9_38},
    {3, arcs_9_39},
    {4, arcs_9_40},
    {1, arcs_9_41},
};
static const arc arcs_10_0[1] = {
    {60, 1},
};
static const arc arcs_10_1[2] = {
    {79, 2},
    {0, 1},
};
static const arc arcs_10_2[1] = {
    {80, 3},
};
static const arc arcs_10_3[1] = {
    {0, 3},
};
static state states_10[4] = {
    {1, arcs_10_0},
    {2, arcs_10_1},
    {1, arcs_10_2},
    {1, arcs_10_3},
};
static const arc arcs_11_0[3] = {
    {6, 1},
    {84, 2},
    {90, 3},
};
static const arc arcs_11_1[3] = {
    {86, 4},
    {90, 5},
    {0, 1},
};
static const arc arcs_11_2[1] = {
    {90, 6},
};
static const arc arcs_11_3[3] = {
    {86, 7},
    {87, 8},
    {0, 3},
};
static const arc arcs_11_4[3] = {
    {84, 2},
    {90, 9},
    {0, 4},
};
static const arc arcs_11_5[2] = {
    {86, 4},
    {0, 5},
};
static const arc arcs_11_6[2] = {
    {86, 10},
    {0, 6},
};
static const arc arcs_11_7[5] = {
    {6, 11},
    {84, 2},
    {88, 12},
    {90, 3},
    {0, 7},
};
static const arc arcs_11_8[1] = {
    {80, 13},
};
static const arc arcs_11_9[3] = {
    {86, 4},
    {87, 14},
    {0, 9},
};
static const arc arcs_11_10[1] = {
    {0, 10},
};
static const arc arcs_11_11[3] = {
    {86, 15},
    {90, 16},
    {0, 11},
};
static const arc arcs_11_12[2] = {
    {86, 17},
    {0, 12},
};
static const arc arcs_11_13[2] = {
    {86, 7},
    {0, 13},
};
static const arc arcs_11_14[1] = {
    {80, 5},
};
static const arc arcs_11_15[3] = {
    {84, 2},
    {90, 18},
    {0, 15},
};
static const arc arcs_11_16[2] = {
    {86, 15},
    {0, 16},
};
static const arc arcs_11_17[4] = {
    {6, 19},
    {84, 2},
    {90, 20},
    {0, 17},
};
static const arc arcs_11_18[3] = {
    {86, 15},
    {87, 21},
    {0, 18},
};
static const arc arcs_11_19[3] = {
    {86, 22},
    {90, 23},
    {0, 19},
};
static const arc arcs_11_20[3] = {
    {86, 24},
    {87, 25},
    {0, 20},
};
static const arc arcs_11_21[1] = {
    {80, 16},
};
static const arc arcs_11_22[3] = {
    {84, 2},
    {90, 26},
    {0, 22},
};
static const arc arcs_11_23[2] = {
    {86, 22},
    {0, 23},
};
static const arc arcs_11_24[4] = {
    {6, 27},
    {84, 2},
    {90, 20},
    {0, 24},
};
static const arc arcs_11_25[1] = {
    {80, 28},
};
static const arc arcs_11_26[3] = {
    {86, 22},
    {87, 29},
    {0, 26},
};
static const arc arcs_11_27[3] = {
    {86, 30},
    {90, 31},
    {0, 27},
};
static const arc arcs_11_28[2] = {
    {86, 24},
    {0, 28},
};
static const arc arcs_11_29[1] = {
    {80, 23},
};
static const arc arcs_11_30[3] = {
    {84, 2},
    {90, 32},
    {0, 30},
};
static const arc arcs_11_31[2] = {
    {86, 30},
    {0, 31},
};
static const arc arcs_11_32[3] = {
    {86, 30},
    {87, 33},
    {0, 32},
};
static const arc arcs_11_33[1] = {
    {80, 31},
};
static state states_11[34] = {
    {3, arcs_11_0},
    {3, arcs_11_1},
    {1, arcs_11_2},
    {3, arcs_11_3},
    {3, arcs_11_4},
    {2, arcs_11_5},
    {2, arcs_11_6},
    {5, arcs_11_7},
    {1, arcs_11_8},
    {3, arcs_11_9},
    {1, arcs_11_10},
    {3, arcs_11_11},
    {2, arcs_11_12},
    {2, arcs_11_13},
    {1, arcs_11_14},
    {3, arcs_11_15},
    {2, arcs_11_16},
    {4, arcs_11_17},
    {3, arcs_11_18},
    {3, arcs_11_19},
    {3, arcs_11_20},
    {1, arcs_11_21},
    {3, arcs_11_22},
    {2, arcs_11_23},
    {4, arcs_11_24},
    {1, arcs_11_25},
    {3, arcs_11_26},
    {3, arcs_11_27},
    {2, arcs_11_28},
    {1, arcs_11_29},
    {3, arcs_11_30},
    {2, arcs_11_31},
    {3, arcs_11_32},
    {1, arcs_11_33},
};
static const arc arcs_12_0[1] = {
    {60, 1},
};
static const arc arcs_12_1[1] = {
    {0, 1},
};
static state states_12[2] = {
    {1, arcs_12_0},
    {1, arcs_12_1},
};
static const arc arcs_13_0[2] = {
    {3, 1},
    {4, 1},
};
static const arc arcs_13_1[1] = {
    {0, 1},
};
static state states_13[2] = {
    {2, arcs_13_0},
    {1, arcs_13_1},
};
static const arc arcs_14_0[1] = {
    {91, 1},
};
static const arc arcs_14_1[2] = {
    {92, 2},
    {2, 3},
};
static const arc arcs_14_2[2] = {
    {2, 3},
    {91, 1},
};
static const arc arcs_14_3[1] = {
    {0, 3},
};
static state states_14[4] = {
    {1, arcs_14_0},
    {2, arcs_14_1},
    {2, arcs_14_2},
    {1, arcs_14_3},
};
static const arc arcs_15_0[8] = {
    {93, 1},
    {94, 1},
    {95, 1},
    {96, 1},
    {97, 1},
    {98, 1},
    {99, 1},
    {100, 1},
};
static const arc arcs_15_1[1] = {
    {0, 1},
};
static state states_15[2] = {
    {8, arcs_15_0},
    {1, arcs_15_1},
};
static const arc arcs_16_0[1] = {
    {101, 1},
};
static const arc arcs_16_1[4] = {
    {87, 2},
    {102, 3},
    {103, 4},
    {0, 1},
};
static const arc arcs_16_2[2] = {
    {101, 5},
    {104, 5},
};
static const arc arcs_16_3[1] = {
    {0, 3},
};
static const arc arcs_16_4[2] = {
    {67, 3},
    {104, 3},
};
static const arc arcs_16_5[3] = {
    {87, 2},
    {81, 3},
    {0, 5},
};
static state states_16[6] = {
    {1, arcs_16_0},
    {4, arcs_16_1},
    {2, arcs_16_2},
    {1, arcs_16_3},
    {2, arcs_16_4},
    {3, arcs_16_5},
};
static const arc arcs_17_0[1] = {
    {79, 1},
};
static const arc arcs_17_1[1] = {
    {80, 2},
};
static const arc arcs_17_2[2] = {
    {87, 3},
    {0, 2},
};
static const arc arcs_17_3[2] = {
    {101, 4},
    {104, 4},
};
static const arc arcs_17_4[1] = {
    {0, 4},
};
static state states_17[5] = {
    {1, arcs_17_0},
    {1, arcs_17_1},
    {2, arcs_17_2},
    {2, arcs_17_3},
    {1, arcs_17_4},
};
static const arc arcs_18_0[2] = {
    {105, 1},
    {80, 1},
};
static const arc arcs_18_1[2] = {
    {86, 2},
    {0, 1},
};
static const arc arcs_18_2[3] = {
    {105, 1},
    {80, 1},
    {0, 2},
};
static state states_18[3] = {
    {2, arcs_18_0},
    {2, arcs_18_1},
    {3, arcs_18_2},
};
static const arc arcs_19_0[13] = {
    {106, 1},
    {107, 1},
    {108, 1},
    {109, 1},
    {110, 1},
    {111, 1},
    {112, 1},
    {113, 1},
    {114, 1},
    {115, 1},
    {116, 1},
    {117, 1},
    {118, 1},
};
static const arc arcs_19_1[1] = {
    {0, 1},
};
static state states_19[2] = {
    {13, arcs_19_0},
    {1, arcs_19_1},
};
static const arc arcs_20_0[2] = {
    {25, 1},
    {48, 1},
};
static const arc arcs_20_1[1] = {
    {119, 2},
};
static const arc arcs_20_2[1] = {
    {0, 2},
};
static state states_20[3] = {
    {2, arcs_20_0},
    {1, arcs_20_1},
    {1, arcs_20_2},
};
static const arc arcs_21_0[2] = {
    {42, 1},
    {43, 1},
};
static const arc arcs_21_1[1] = {
    {0, 1},
};
static state states_21[2] = {
    {2, arcs_21_0},
    {1, arcs_21_1},
};
static const arc arcs_22_0[5] = {
    {120, 1},
    {121, 1},
    {122, 1},
    {123, 1},
    {124, 1},
};
static const arc arcs_22_1[1] = {
    {0, 1},
};
static state states_22[2] = {
    {5, arcs_22_0},
    {1, arcs_22_1},
};
static const arc arcs_23_0[2] = {
    {21, 1},
    {36, 1},
};
static const arc arcs_23_1[1] = {
    {0, 1},
};
static state states_23[2] = {
    {2, arcs_23_0},
    {1, arcs_23_1},
};
static const arc arcs_24_0[2] = {
    {23, 1},
    {27, 1},
};
static const arc arcs_24_1[1] = {
    {0, 1},
};
static state states_24[2] = {
    {2, arcs_24_0},
    {1, arcs_24_1},
};
static const arc arcs_25_0[2] = {
    {45, 1},
    {46, 1},
};
static const arc arcs_25_1[2] = {
    {101, 2},
    {0, 1},
};
static const arc arcs_25_2[1] = {
    {0, 2},
};
static state states_25[3] = {
    {2, arcs_25_0},
    {2, arcs_25_1},
    {1, arcs_25_2},
};
static const arc arcs_26_0[1] = {
    {104, 1},
};
static const arc arcs_26_1[1] = {
    {0, 1},
};
static state states_26[2] = {
    {1, arcs_26_0},
    {1, arcs_26_1},
};
static const arc arcs_27_0[2] = {
    {19, 1},
    {44, 2},
};
static const arc arcs_27_1[2] = {
    {80, 3},
    {0, 1},
};
static const arc arcs_27_2[2] = {
    {80, 4},
    {0, 2},
};
static const arc arcs_27_3[2] = {
    {38, 5},
    {0, 3},
};
static const arc arcs_27_4[2] = {
    {29, 5},
    {0, 4},
};
static const arc arcs_27_5[1] = {
    {80, 6},
};
static const arc arcs_27_6[1] = {
    {0, 6},
};
static state states_27[7] = {
    {2, arcs_27_0},
    {2, arcs_27_1},
    {2, arcs_27_2},
    {2, arcs_27_3},
    {2, arcs_27_4},
    {1, arcs_27_5},
    {1, arcs_27_6},
};
static const arc arcs_28_0[2] = {
    {125, 1},
    {126, 1},
};
static const arc arcs_28_1[1] = {
    {0, 1},
};
static state states_28[2] = {
    {2, arcs_28_0},
    {1, arcs_28_1},
};
static const arc arcs_29_0[2] = {
    {18, 1},
    {33, 1},
};
static const arc arcs_29_1[1] = {
    {127, 2},
};
static const arc arcs_29_2[1] = {
    {0, 2},
};
static state states_29[3] = {
    {2, arcs_29_0},
    {1, arcs_29_1},
    {1, arcs_29_2},
};
static const arc arcs_30_0[2] = {
    {29, 1},
    {38, 2},
};
static const arc arcs_30_1[3] = {
    {128, 3},
    {9, 3},
    {69, 4},
};
static const arc arcs_30_2[3] = {
    {128, 5},
    {9, 5},
    {69, 6},
};
static const arc arcs_30_3[4] = {
    {128, 3},
    {9, 3},
    {33, 7},
    {69, 4},
};
static const arc arcs_30_4[1] = {
    {33, 7},
};
static const arc arcs_30_5[4] = {
    {128, 5},
    {9, 5},
    {18, 7},
    {69, 6},
};
static const arc arcs_30_6[1] = {
    {18, 7},
};
static const arc arcs_30_7[3] = {
    {5, 8},
    {6, 9},
    {129, 9},
};
static const arc arcs_30_8[1] = {
    {129, 10},
};
static const arc arcs_30_9[1] = {
    {0, 9},
};
static const arc arcs_30_10[1] = {
    {70, 9},
};
static state states_30[11] = {
    {2, arcs_30_0},
    {3, arcs_30_1},
    {3, arcs_30_2},
    {4, arcs_30_3},
    {1, arcs_30_4},
    {4, arcs_30_5},
    {1, arcs_30_6},
    {3, arcs_30_7},
    {1, arcs_30_8},
    {1, arcs_30_9},
    {1, arcs_30_10},
};
static const arc arcs_31_0[1] = {
    {60, 1},
};
static const arc arcs_31_1[3] = {
    {131, 2},
    {132, 2},
    {0, 1},
};
static const arc arcs_31_2[1] = {
    {60, 3},
};
static const arc arcs_31_3[1] = {
    {0, 3},
};
static state states_31[4] = {
    {1, arcs_31_0},
    {3, arcs_31_1},
    {1, arcs_31_2},
    {1, arcs_31_3},
};
static const arc arcs_32_0[1] = {
    {69, 1},
};
static const arc arcs_32_1[3] = {
    {131, 2},
    {132, 2},
    {0, 1},
};
static const arc arcs_32_2[1] = {
    {60, 3},
};
static const arc arcs_32_3[1] = {
    {0, 3},
};
static state states_32[4] = {
    {1, arcs_32_0},
    {3, arcs_32_1},
    {1, arcs_32_2},
    {1, arcs_32_3},
};
static const arc arcs_33_0[1] = {
    {130, 1},
};
static const arc arcs_33_1[2] = {
    {86, 2},
    {0, 1},
};
static const arc arcs_33_2[2] = {
    {130, 1},
    {0, 2},
};
static state states_33[3] = {
    {1, arcs_33_0},
    {2, arcs_33_1},
    {2, arcs_33_2},
};
static const arc arcs_34_0[1] = {
    {133, 1},
};
static const arc arcs_34_1[2] = {
    {86, 0},
    {0, 1},
};
static state states_34[2] = {
    {1, arcs_34_0},
    {2, arcs_34_1},
};
static const arc arcs_35_0[1] = {
    {60, 1},
};
static const arc arcs_35_1[2] = {
    {128, 0},
    {0, 1},
};
static state states_35[2] = {
    {1, arcs_35_0},
    {2, arcs_35_1},
};
static const arc arcs_36_0[1] = {
    {30, 1},
};
static const arc arcs_36_1[1] = {
    {60, 2},
};
static const arc arcs_36_2[2] = {
    {86, 1},
    {0, 2},
};
static state states_36[3] = {
    {1, arcs_36_0},
    {1, arcs_36_1},
    {2, arcs_36_2},
};
static const arc arcs_37_0[1] = {
    {40, 1},
};
static const arc arcs_37_1[1] = {
    {60, 2},
};
static const arc arcs_37_2[2] = {
    {86, 1},
    {0, 2},
};
static state states_37[3] = {
    {1, arcs_37_0},
    {1, arcs_37_1},
    {2, arcs_37_2},
};
static const arc arcs_38_0[1] = {
    {20, 1},
};
static const arc arcs_38_1[1] = {
    {80, 2},
};
static const arc arcs_38_2[2] = {
    {86, 3},
    {0, 2},
};
static const arc arcs_38_3[1] = {
    {80, 4},
};
static const arc arcs_38_4[1] = {
    {0, 4},
};
static state states_38[5] = {
    {1, arcs_38_0},
    {1, arcs_38_1},
    {2, arcs_38_2},
    {1, arcs_38_3},
    {1, arcs_38_4},
};
static const arc arcs_39_0[9] = {
    {134, 1},
    {75, 1},
    {73, 1},
    {135, 1},
    {76, 1},
    {136, 1},
    {137, 1},
    {138, 1},
    {139, 1},
};
static const arc arcs_39_1[1] = {
    {0, 1},
};
static state states_39[2] = {
    {9, arcs_39_0},
    {1, arcs_39_1},
};
static const arc arcs_40_0[1] = {
    {58, 1},
};
static const arc arcs_40_1[3] = {
    {135, 2},
    {76, 2},
    {139, 2},
};
static const arc arcs_40_2[1] = {
    {0, 2},
};
static state states_40[3] = {
    {1, arcs_40_0},
    {3, arcs_40_1},
    {1, arcs_40_2},
};
static const arc arcs_41_0[2] = {
    {31, 1},
    {32, 2},
};
static const arc arcs_41_1[1] = {
    {140, 3},
};
static const arc arcs_41_2[1] = {
    {140, 4},
};
static const arc arcs_41_3[1] = {
    {79, 5},
};
static const arc arcs_41_4[1] = {
    {79, 6},
};
static const arc arcs_41_5[1] = {
    {141, 7},
};
static const arc arcs_41_6[1] = {
    {141, 8},
};
static const arc arcs_41_7[3] = {
    {142, 1},
    {143, 9},
    {0, 7},
};
static const arc arcs_41_8[3] = {
    {144, 9},
    {145, 2},
    {0, 8},
};
static const arc arcs_41_9[1] = {
    {79, 10},
};
static const arc arcs_41_10[1] = {
    {141, 11},
};
static const arc arcs_41_11[1] = {
    {0, 11},
};
static state states_41[12] = {
    {2, arcs_41_0},
    {1, arcs_41_1},
    {1, arcs_41_2},
    {1, arcs_41_3},
    {1, arcs_41_4},
    {1, arcs_41_5},
    {1, arcs_41_6},
    {3, arcs_41_7},
    {3, arcs_41_8},
    {1, arcs_41_9},
    {1, arcs_41_10},
    {1, arcs_41_11},
};
static const arc arcs_42_0[2] = {
    {52, 1},
    {53, 2},
};
static const arc arcs_42_1[1] = {
    {140, 3},
};
static const arc arcs_42_2[1] = {
    {140, 4},
};
static const arc arcs_42_3[1] = {
    {79, 5},
};
static const arc arcs_42_4[1] = {
    {79, 6},
};
static const arc arcs_42_5[1] = {
    {141, 7},
};
static const arc arcs_42_6[1] = {
    {141, 8},
};
static const arc arcs_42_7[2] = {
    {144, 9},
    {0, 7},
};
static const arc arcs_42_8[2] = {
    {143, 9},
    {0, 8},
};
static const arc arcs_42_9[1] = {
    {79, 10},
};
static const arc arcs_42_10[1] = {
    {141, 11},
};
static const arc arcs_42_11[1] = {
    {0, 11},
};
static state states_42[12] = {
    {2, arcs_42_0},
    {1, arcs_42_1},
    {1, arcs_42_2},
    {1, arcs_42_3},
    {1, arcs_42_4},
    {1, arcs_42_5},
    {1, arcs_42_6},
    {2, arcs_42_7},
    {2, arcs_42_8},
    {1, arcs_42_9},
    {1, arcs_42_10},
    {1, arcs_42_11},
};
static const arc arcs_43_0[2] = {
    {28, 1},
    {35, 2},
};
static const arc arcs_43_1[1] = {
    {119, 3},
};
static const arc arcs_43_2[1] = {
    {119, 4},
};
static const arc arcs_43_3[1] = {
    {146, 5},
};
static const arc arcs_43_4[1] = {
    {147, 6},
};
static const arc arcs_43_5[1] = {
    {67, 7},
};
static const arc arcs_43_6[1] = {
    {67, 8},
};
static const arc arcs_43_7[1] = {
    {79, 9},
};
static const arc arcs_43_8[1] = {
    {79, 10},
};
static const arc arcs_43_9[2] = {
    {81, 11},
    {141, 12},
};
static const arc arcs_43_10[2] = {
    {81, 13},
    {141, 14},
};
static const arc arcs_43_11[1] = {
    {141, 12},
};
static const arc arcs_43_12[2] = {
    {143, 15},
    {0, 12},
};
static const arc arcs_43_13[1] = {
    {141, 14},
};
static const arc arcs_43_14[2] = {
    {144, 15},
    {0, 14},
};
static const arc arcs_43_15[1] = {
    {79, 16},
};
static const arc arcs_43_16[1] = {
    {141, 17},
};
static const arc arcs_43_17[1] = {
    {0, 17},
};
static state states_43[18] = {
    {2, arcs_43_0},
    {1, arcs_43_1},
    {1, arcs_43_2},
    {1, arcs_43_3},
    {1, arcs_43_4},
    {1, arcs_43_5},
    {1, arcs_43_6},
    {1, arcs_43_7},
    {1, arcs_43_8},
    {2, arcs_43_9},
    {2, arcs_43_10},
    {1, arcs_43_11},
    {2, arcs_43_12},
    {1, arcs_43_13},
    {2, arcs_43_14},
    {1, arcs_43_15},
    {1, arcs_43_16},
    {1, arcs_43_17},
};
static const arc arcs_44_0[2] = {
    {34, 1},
    {49, 2},
};
static const arc arcs_44_1[1] = {
    {79, 3},
};
static const arc arcs_44_2[1] = {
    {79, 4},
};
static const arc arcs_44_3[1] = {
    {141, 5},
};
static const arc arcs_44_4[1] = {
    {141, 6},
};
static const arc arcs_44_5[2] = {
    {148, 7},
    {149, 8},
};
static const arc arcs_44_6[2] = {
    {150, 7},
    {149, 9},
};
static const arc arcs_44_7[1] = {
    {79, 10},
};
static const arc arcs_44_8[1] = {
    {79, 11},
};
static const arc arcs_44_9[1] = {
    {79, 12},
};
static const arc arcs_44_10[1] = {
    {141, 13},
};
static const arc arcs_44_11[1] = {
    {141, 14},
};
static const arc arcs_44_12[1] = {
    {141, 15},
};
static const arc arcs_44_13[1] = {
    {0, 13},
};
static const arc arcs_44_14[4] = {
    {144, 16},
    {148, 7},
    {149, 8},
    {0, 14},
};
static const arc arcs_44_15[4] = {
    {143, 17},
    {150, 7},
    {149, 9},
    {0, 15},
};
static const arc arcs_44_16[1] = {
    {79, 18},
};
static const arc arcs_44_17[1] = {
    {79, 19},
};
static const arc arcs_44_18[1] = {
    {141, 20},
};
static const arc arcs_44_19[1] = {
    {141, 21},
};
static const arc arcs_44_20[2] = {
    {148, 7},
    {0, 20},
};
static const arc arcs_44_21[2] = {
    {150, 7},
    {0, 21},
};
static state states_44[22] = {
    {2, arcs_44_0},
    {1, arcs_44_1},
    {1, arcs_44_2},
    {1, arcs_44_3},
    {1, arcs_44_4},
    {2, arcs_44_5},
    {2, arcs_44_6},
    {1, arcs_44_7},
    {1, arcs_44_8},
    {1, arcs_44_9},
    {1, arcs_44_10},
    {1, arcs_44_11},
    {1, arcs_44_12},
    {1, arcs_44_13},
    {4, arcs_44_14},
    {4, arcs_44_15},
    {1, arcs_44_16},
    {1, arcs_44_17},
    {1, arcs_44_18},
    {1, arcs_44_19},
    {2, arcs_44_20},
    {2, arcs_44_21},
};
static const arc arcs_45_0[2] = {
    {51, 1},
    {54, 2},
};
static const arc arcs_45_1[1] = {
    {151, 3},
};
static const arc arcs_45_2[1] = {
    {151, 4},
};
static const arc arcs_45_3[2] = {
    {86, 1},
    {79, 5},
};
static const arc arcs_45_4[2] = {
    {86, 2},
    {79, 5},
};
static const arc arcs_45_5[2] = {
    {81, 6},
    {141, 7},
};
static const arc arcs_45_6[1] = {
    {141, 7},
};
static const arc arcs_45_7[1] = {
    {0, 7},
};
static state states_45[8] = {
    {2, arcs_45_0},
    {1, arcs_45_1},
    {1, arcs_45_2},
    {2, arcs_45_3},
    {2, arcs_45_4},
    {2, arcs_45_5},
    {1, arcs_45_6},
    {1, arcs_45_7},
};
static const arc arcs_46_0[1] = {
    {80, 1},
};
static const arc arcs_46_1[3] = {
    {131, 2},
    {132, 2},
    {0, 1},
};
static const arc arcs_46_2[1] = {
    {152, 3},
};
static const arc arcs_46_3[1] = {
    {0, 3},
};
static state states_46[4] = {
    {1, arcs_46_0},
    {3, arcs_46_1},
    {1, arcs_46_2},
    {1, arcs_46_3},
};
static const arc arcs_47_0[2] = {
    {153, 1},
    {154, 2},
};
static const arc arcs_47_1[2] = {
    {80, 3},
    {0, 1},
};
static const arc arcs_47_2[2] = {
    {80, 4},
    {0, 2},
};
static const arc arcs_47_3[2] = {
    {131, 5},
    {0, 3},
};
static const arc arcs_47_4[2] = {
    {132, 5},
    {0, 4},
};
static const arc arcs_47_5[1] = {
    {60, 6},
};
static const arc arcs_47_6[1] = {
    {0, 6},
};
static state states_47[7] = {
    {2, arcs_47_0},
    {2, arcs_47_1},
    {2, arcs_47_2},
    {2, arcs_47_3},
    {2, arcs_47_4},
    {1, arcs_47_5},
    {1, arcs_47_6},
};
static const arc arcs_48_0[2] = {
    {2, 1},
    {4, 2},
};
static const arc arcs_48_1[1] = {
    {155, 3},
};
static const arc arcs_48_2[1] = {
    {0, 2},
};
static const arc arcs_48_3[1] = {
    {65, 4},
};
static const arc arcs_48_4[2] = {
    {156, 2},
    {65, 4},
};
static state states_48[5] = {
    {2, arcs_48_0},
    {1, arcs_48_1},
    {1, arcs_48_2},
    {1, arcs_48_3},
    {2, arcs_48_4},
};
static const arc arcs_49_0[1] = {
    {80, 1},
};
static const arc arcs_49_1[2] = {
    {157, 2},
    {0, 1},
};
static const arc arcs_49_2[1] = {
    {80, 3},
};
static const arc arcs_49_3[1] = {
    {0, 3},
};
static state states_49[4] = {
    {1, arcs_49_0},
    {2, arcs_49_1},
    {1, arcs_49_2},
    {1, arcs_49_3},
};
static const arc arcs_50_0[2] = {
    {158, 1},
    {159, 2},
};
static const arc arcs_50_1[1] = {
    {0, 1},
};
static const arc arcs_50_2[3] = {
    {31, 3},
    {32, 4},
    {0, 2},
};
static const arc arcs_50_3[1] = {
    {159, 5},
};
static const arc arcs_50_4[1] = {
    {159, 6},
};
static const arc arcs_50_5[1] = {
    {143, 7},
};
static const arc arcs_50_6[1] = {
    {144, 7},
};
static const arc arcs_50_7[1] = {
    {80, 1},
};
static state states_50[8] = {
    {2, arcs_50_0},
    {1, arcs_50_1},
    {3, arcs_50_2},
    {1, arcs_50_3},
    {1, arcs_50_4},
    {1, arcs_50_5},
    {1, arcs_50_6},
    {1, arcs_50_7},
};
static const arc arcs_51_0[2] = {
    {161, 1},
    {159, 1},
};
static const arc arcs_51_1[1] = {
    {0, 1},
};
static state states_51[2] = {
    {2, arcs_51_0},
    {1, arcs_51_1},
};
static const arc arcs_52_0[1] = {
    {39, 1},
};
static const arc arcs_52_1[2] = {
    {79, 2},
    {89, 3},
};
static const arc arcs_52_2[1] = {
    {80, 4},
};
static const arc arcs_52_3[1] = {
    {79, 2},
};
static const arc arcs_52_4[1] = {
    {0, 4},
};
static state states_52[5] = {
    {1, arcs_52_0},
    {2, arcs_52_1},
    {1, arcs_52_2},
    {1, arcs_52_3},
    {1, arcs_52_4},
};
static const arc arcs_53_0[1] = {
    {39, 1},
};
static const arc arcs_53_1[2] = {
    {79, 2},
    {89, 3},
};
static const arc arcs_53_2[1] = {
    {160, 4},
};
static const arc arcs_53_3[1] = {
    {79, 2},
};
static const arc arcs_53_4[1] = {
    {0, 4},
};
static state states_53[5] = {
    {1, arcs_53_0},
    {2, arcs_53_1},
    {1, arcs_53_2},
    {1, arcs_53_3},
    {1, arcs_53_4},
};
static const arc arcs_54_0[1] = {
    {162, 1},
};
static const arc arcs_54_1[3] = {
    {163, 2},
    {164, 3},
    {0, 1},
};
static const arc arcs_54_2[1] = {
    {162, 4},
};
static const arc arcs_54_3[1] = {
    {162, 5},
};
static const arc arcs_54_4[2] = {
    {163, 2},
    {0, 4},
};
static const arc arcs_54_5[2] = {
    {164, 3},
    {0, 5},
};
static state states_54[6] = {
    {1, arcs_54_0},
    {3, arcs_54_1},
    {1, arcs_54_2},
    {1, arcs_54_3},
    {2, arcs_54_4},
    {2, arcs_54_5},
};
static const arc arcs_55_0[1] = {
    {165, 1},
};
static const arc arcs_55_1[3] = {
    {166, 2},
    {167, 3},
    {0, 1},
};
static const arc arcs_55_2[1] = {
    {165, 4},
};
static const arc arcs_55_3[1] = {
    {165, 5},
};
static const arc arcs_55_4[2] = {
    {166, 2},
    {0, 4},
};
static const arc arcs_55_5[2] = {
    {167, 3},
    {0, 5},
};
static state states_55[6] = {
    {1, arcs_55_0},
    {3, arcs_55_1},
    {1, arcs_55_2},
    {1, arcs_55_3},
    {2, arcs_55_4},
    {2, arcs_55_5},
};
static const arc arcs_56_0[3] = {
    {41, 1},
    {47, 1},
    {168, 2},
};
static const arc arcs_56_1[1] = {
    {165, 2},
};
static const arc arcs_56_2[1] = {
    {0, 2},
};
static state states_56[3] = {
    {3, arcs_56_0},
    {1, arcs_56_1},
    {1, arcs_56_2},
};
static const arc arcs_57_0[1] = {
    {152, 1},
};
static const arc arcs_57_1[2] = {
    {169, 0},
    {0, 1},
};
static state states_57[2] = {
    {1, arcs_57_0},
    {2, arcs_57_1},
};
static const arc arcs_58_0[13] = {
    {170, 1},
    {171, 1},
    {172, 1},
    {170, 1},
    {173, 1},
    {174, 1},
    {175, 1},
    {176, 2},
    {146, 1},
    {177, 3},
    {147, 1},
    {178, 4},
    {41, 5},
};
static const arc arcs_58_1[1] = {
    {0, 1},
};
static const arc arcs_58_2[1] = {
    {147, 1},
};
static const arc arcs_58_3[2] = {
    {41, 1},
    {0, 3},
};
static const arc arcs_58_4[2] = {
    {47, 1},
    {0, 4},
};
static const arc arcs_58_5[1] = {
    {146, 1},
};
static state states_58[6] = {
    {13, arcs_58_0},
    {1, arcs_58_1},
    {1, arcs_58_2},
    {2, arcs_58_3},
    {2, arcs_58_4},
    {1, arcs_58_5},
};
static const arc arcs_59_0[1] = {
    {6, 1},
};
static const arc arcs_59_1[1] = {
    {152, 2},
};
static const arc arcs_59_2[1] = {
    {0, 2},
};
static state states_59[3] = {
    {1, arcs_59_0},
    {1, arcs_59_1},
    {1, arcs_59_2},
};
static const arc arcs_60_0[1] = {
    {179, 1},
};
static const arc arcs_60_1[2] = {
    {180, 0},
    {0, 1},
};
static state states_60[2] = {
    {1, arcs_60_0},
    {2, arcs_60_1},
};
static const arc arcs_61_0[1] = {
    {181, 1},
};
static const arc arcs_61_1[2] = {
    {182, 0},
    {0, 1},
};
static state states_61[2] = {
    {1, arcs_61_0},
    {2, arcs_61_1},
};
static const arc arcs_62_0[1] = {
    {183, 1},
};
static const arc arcs_62_1[2] = {
    {184, 0},
    {0, 1},
};
static state states_62[2] = {
    {1, arcs_62_0},
    {2, arcs_62_1},
};
static const arc arcs_63_0[1] = {
    {185, 1},
};
static const arc arcs_63_1[3] = {
    {186, 0},
    {187, 0},
    {0, 1},
};
static state states_63[2] = {
    {1, arcs_63_0},
    {3, arcs_63_1},
};
static const arc arcs_64_0[1] = {
    {188, 1},
};
static const arc arcs_64_1[3] = {
    {7, 0},
    {8, 0},
    {0, 1},
};
static state states_64[2] = {
    {1, arcs_64_0},
    {3, arcs_64_1},
};
static const arc arcs_65_0[1] = {
    {189, 1},
};
static const arc arcs_65_1[6] = {
    {190, 0},
    {6, 0},
    {88, 0},
    {191, 0},
    {10, 0},
    {0, 1},
};
static state states_65[2] = {
    {1, arcs_65_0},
    {6, arcs_65_1},
};
static const arc arcs_66_0[4] = {
    {7, 1},
    {8, 1},
    {57, 1},
    {192, 2},
};
static const arc arcs_66_1[1] = {
    {189, 2},
};
static const arc arcs_66_2[1] = {
    {0, 2},
};
static state states_66[3] = {
    {4, arcs_66_0},
    {1, arcs_66_1},
    {1, arcs_66_2},
};
static const arc arcs_67_0[1] = {
    {193, 1},
};
static const arc arcs_67_1[2] = {
    {84, 2},
    {0, 1},
};
static const arc arcs_67_2[1] = {
    {189, 3},
};
static const arc arcs_67_3[1] = {
    {0, 3},
};
static state states_67[4] = {
    {1, arcs_67_0},
    {2, arcs_67_1},
    {1, arcs_67_2},
    {1, arcs_67_3},
};
static const arc arcs_68_0[2] = {
    {59, 1},
    {194, 2},
};
static const arc arcs_68_1[1] = {
    {194, 2},
};
static const arc arcs_68_2[2] = {
    {195, 2},
    {0, 2},
};
static state states_68[3] = {
    {2, arcs_68_0},
    {1, arcs_68_1},
    {2, arcs_68_2},
};
static const arc arcs_69_0[13] = {
    {5, 1},
    {9, 2},
    {11, 2},
    {12, 2},
    {13, 2},
    {14, 2},
    {15, 2},
    {16, 2},
    {17, 3},
    {56, 4},
    {60, 2},
    {61, 2},
    {62, 5},
};
static const arc arcs_69_1[3] = {
    {70, 2},
    {196, 6},
    {104, 6},
};
static const arc arcs_69_2[1] = {
    {0, 2},
};
static const arc arcs_69_3[2] = {
    {197, 2},
    {196, 7},
};
static const arc arcs_69_4[2] = {
    {198, 2},
    {199, 8},
};
static const arc arcs_69_5[2] = {
    {62, 5},
    {0, 5},
};
static const arc arcs_69_6[1] = {
    {70, 2},
};
static const arc arcs_69_7[1] = {
    {197, 2},
};
static const arc arcs_69_8[1] = {
    {198, 2},
};
static state states_69[9] = {
    {13, arcs_69_0},
    {3, arcs_69_1},
    {1, arcs_69_2},
    {2, arcs_69_3},
    {2, arcs_69_4},
    {2, arcs_69_5},
    {1, arcs_69_6},
    {1, arcs_69_7},
    {1, arcs_69_8},
};
static const arc arcs_70_0[2] = {
    {140, 1},
    {105, 1},
};
static const arc arcs_70_1[3] = {
    {86, 2},
    {200, 3},
    {0, 1},
};
static const arc arcs_70_2[3] = {
    {140, 4},
    {105, 4},
    {0, 2},
};
static const arc arcs_70_3[1] = {
    {0, 3},
};
static const arc arcs_70_4[2] = {
    {86, 2},
    {0, 4},
};
static state states_70[5] = {
    {2, arcs_70_0},
    {3, arcs_70_1},
    {3, arcs_70_2},
    {1, arcs_70_3},
    {2, arcs_70_4},
};
static const arc arcs_71_0[3] = {
    {5, 1},
    {128, 2},
    {17, 3},
};
static const arc arcs_71_1[2] = {
    {70, 4},
    {71, 5},
};
static const arc arcs_71_2[1] = {
    {60, 4},
};
static const arc arcs_71_3[1] = {
    {201, 6},
};
static const arc arcs_71_4[1] = {
    {0, 4},
};
static const arc arcs_71_5[1] = {
    {70, 4},
};
static const arc arcs_71_6[1] = {
    {197, 4},
};
static state states_71[7] = {
    {3, arcs_71_0},
    {2, arcs_71_1},
    {1, arcs_71_2},
    {1, arcs_71_3},
    {1, arcs_71_4},
    {1, arcs_71_5},
    {1, arcs_71_6},
};
static const arc arcs_72_0[1] = {
    {202, 1},
};
static const arc arcs_72_1[2] = {
    {86, 2},
    {0, 1},
};
static const arc arcs_72_2[2] = {
    {202, 1},
    {0, 2},
};
static state states_72[3] = {
    {1, arcs_72_0},
    {2, arcs_72_1},
    {2, arcs_72_2},
};
static const arc arcs_73_0[2] = {
    {79, 1},
    {80, 2},
};
static const arc arcs_73_1[3] = {
    {203, 3},
    {80, 4},
    {0, 1},
};
static const arc arcs_73_2[2] = {
    {79, 1},
    {0, 2},
};
static const arc arcs_73_3[1] = {
    {0, 3},
};
static const arc arcs_73_4[2] = {
    {203, 3},
    {0, 4},
};
static state states_73[5] = {
    {2, arcs_73_0},
    {3, arcs_73_1},
    {2, arcs_73_2},
    {1, arcs_73_3},
    {2, arcs_73_4},
};
static const arc arcs_74_0[1] = {
    {79, 1},
};
static const arc arcs_74_1[2] = {
    {80, 2},
    {0, 1},
};
static const arc arcs_74_2[1] = {
    {0, 2},
};
static state states_74[3] = {
    {1, arcs_74_0},
    {2, arcs_74_1},
    {1, arcs_74_2},
};
static const arc arcs_75_0[2] = {
    {152, 1},
    {105, 1},
};
static const arc arcs_75_1[2] = {
    {86, 2},
    {0, 1},
};
static const arc arcs_75_2[3] = {
    {152, 1},
    {105, 1},
    {0, 2},
};
static state states_75[3] = {
    {2, arcs_75_0},
    {2, arcs_75_1},
    {3, arcs_75_2},
};
static const arc arcs_76_0[1] = {
    {80, 1},
};
static const arc arcs_76_1[2] = {
    {86, 2},
    {0, 1},
};
static const arc arcs_76_2[2] = {
    {80, 1},
    {0, 2},
};
static state states_76[3] = {
    {1, arcs_76_0},
    {2, arcs_76_1},
    {2, arcs_76_2},
};
static const arc arcs_77_0[3] = {
    {84, 1},
    {105, 2},
    {80, 3},
};
static const arc arcs_77_1[1] = {
    {152, 4},
};
static const arc arcs_77_2[3] = {
    {86, 5},
    {200, 6},
    {0, 2},
};
static const arc arcs_77_3[4] = {
    {86, 5},
    {79, 7},
    {200, 6},
    {0, 3},
};
static const arc arcs_77_4[3] = {
    {86, 8},
    {200, 6},
    {0, 4},
};
static const arc arcs_77_5[3] = {
    {105, 9},
    {80, 9},
    {0, 5},
};
static const arc arcs_77_6[1] = {
    {0, 6},
};
static const arc arcs_77_7[1] = {
    {80, 4},
};
static const arc arcs_77_8[3] = {
    {84, 10},
    {80, 11},
    {0, 8},
};
static const arc arcs_77_9[2] = {
    {86, 5},
    {0, 9},
};
static const arc arcs_77_10[1] = {
    {152, 12},
};
static const arc arcs_77_11[1] = {
    {79, 13},
};
static const arc arcs_77_12[2] = {
    {86, 8},
    {0, 12},
};
static const arc arcs_77_13[1] = {
    {80, 12},
};
static state states_77[14] = {
    {3, arcs_77_0},
    {1, arcs_77_1},
    {3, arcs_77_2},
    {4, arcs_77_3},
    {3, arcs_77_4},
    {3, arcs_77_5},
    {1, arcs_77_6},
    {1, arcs_77_7},
    {3, arcs_77_8},
    {2, arcs_77_9},
    {1, arcs_77_10},
    {1, arcs_77_11},
    {2, arcs_77_12},
    {1, arcs_77_13},
};
static const arc arcs_78_0[2] = {
    {22, 1},
    {37, 1},
};
static const arc arcs_78_1[1] = {
    {60, 2},
};
static const arc arcs_78_2[2] = {
    {5, 3},
    {79, 4},
};
static const arc arcs_78_3[2] = {
    {70, 5},
    {71, 6},
};
static const arc arcs_78_4[1] = {
    {141, 7},
};
static const arc arcs_78_5[1] = {
    {79, 4},
};
static const arc arcs_78_6[1] = {
    {70, 5},
};
static const arc arcs_78_7[1] = {
    {0, 7},
};
static state states_78[8] = {
    {2, arcs_78_0},
    {1, arcs_78_1},
    {2, arcs_78_2},
    {2, arcs_78_3},
    {1, arcs_78_4},
    {1, arcs_78_5},
    {1, arcs_78_6},
    {1, arcs_78_7},
};
static const arc arcs_79_0[1] = {
    {204, 1},
};
static const arc arcs_79_1[2] = {
    {86, 2},
    {0, 1},
};
static const arc arcs_79_2[2] = {
    {204, 1},
    {0, 2},
};
static state states_79[3] = {
    {1, arcs_79_0},
    {2, arcs_79_1},
    {2, arcs_79_2},
};
static const arc arcs_80_0[3] = {
    {6, 1},
    {84, 1},
    {80, 2},
};
static const arc arcs_80_1[1] = {
    {80, 3},
};
static const arc arcs_80_2[4] = {
    {157, 1},
    {87, 1},
    {200, 3},
    {0, 2},
};
static const arc arcs_80_3[1] = {
    {0, 3},
};
static state states_80[4] = {
    {3, arcs_80_0},
    {1, arcs_80_1},
    {4, arcs_80_2},
    {1, arcs_80_3},
};
static const arc arcs_81_0[2] = {
    {200, 1},
    {206, 1},
};
static const arc arcs_81_1[1] = {
    {0, 1},
};
static state states_81[2] = {
    {2, arcs_81_0},
    {1, arcs_81_1},
};
static const arc arcs_82_0[2] = {
    {28, 1},
    {35, 2},
};
static const arc arcs_82_1[1] = {
    {119, 3},
};
static const arc arcs_82_2[1] = {
    {119, 4},
};
static const arc arcs_82_3[1] = {
    {146, 5},
};
static const arc arcs_82_4[1] = {
    {147, 5},
};
static const arc arcs_82_5[1] = {
    {159, 6},
};
static const arc arcs_82_6[2] = {
    {205, 7},
    {0, 6},
};
static const arc arcs_82_7[1] = {
    {0, 7},
};
static state states_82[8] = {
    {2, arcs_82_0},
    {1, arcs_82_1},
    {1, arcs_82_2},
    {1, arcs_82_3},
    {1, arcs_82_4},
    {1, arcs_82_5},
    {2, arcs_82_6},
    {1, arcs_82_7},
};
static const arc arcs_83_0[2] = {
    {58, 1},
    {207, 2},
};
static const arc arcs_83_1[1] = {
    {207, 2},
};
static const arc arcs_83_2[1] = {
    {0, 2},
};
static state states_83[3] = {
    {2, arcs_83_0},
    {1, arcs_83_1},
    {1, arcs_83_2},
};
static const arc arcs_84_0[2] = {
    {31, 1},
    {32, 1},
};
static const arc arcs_84_1[1] = {
    {160, 2},
};
static const arc arcs_84_2[2] = {
    {205, 3},
    {0, 2},
};
static const arc arcs_84_3[1] = {
    {0, 3},
};
static state states_84[4] = {
    {2, arcs_84_0},
    {1, arcs_84_1},
    {2, arcs_84_2},
    {1, arcs_84_3},
};
static const arc arcs_85_0[1] = {
    {60, 1},
};
static const arc arcs_85_1[1] = {
    {0, 1},
};
static state states_85[2] = {
    {1, arcs_85_0},
    {1, arcs_85_1},
};
static const arc arcs_86_0[2] = {
    {50, 1},
    {55, 1},
};
static const arc arcs_86_1[2] = {
    {209, 2},
    {0, 1},
};
static const arc arcs_86_2[1] = {
    {0, 2},
};
static state states_86[3] = {
    {2, arcs_86_0},
    {2, arcs_86_1},
    {1, arcs_86_2},
};
static const arc arcs_87_0[3] = {
    {29, 1},
    {38, 1},
    {101, 2},
};
static const arc arcs_87_1[1] = {
    {80, 2},
};
static const arc arcs_87_2[1] = {
    {0, 2},
};
static state states_87[3] = {
    {3, arcs_87_0},
    {1, arcs_87_1},
    {1, arcs_87_2},
};
static const arc arcs_88_0[2] = {
    {2, 1},
    {4, 2},
};
static const arc arcs_88_1[2] = {
    {155, 3},
    {81, 4},
};
static const arc arcs_88_2[1] = {
    {0, 2},
};
static const arc arcs_88_3[1] = {
    {65, 5},
};
static const arc arcs_88_4[1] = {
    {2, 6},
};
static const arc arcs_88_5[2] = {
    {156, 2},
    {65, 5},
};
static const arc arcs_88_6[1] = {
    {155, 3},
};
static state states_88[7] = {
    {2, arcs_88_0},
    {2, arcs_88_1},
    {1, arcs_88_2},
    {1, arcs_88_3},
    {1, arcs_88_4},
    {2, arcs_88_5},
    {1, arcs_88_6},
};
static const arc arcs_89_0[1] = {
    {211, 1},
};
static const arc arcs_89_1[2] = {
    {64, 2},
    {2, 1},
};
static const arc arcs_89_2[1] = {
    {0, 2},
};
static state states_89[3] = {
    {1, arcs_89_0},
    {2, arcs_89_1},
    {1, arcs_89_2},
};
static const arc arcs_90_0[1] = {
    {5, 1},
};
static const arc arcs_90_1[2] = {
    {70, 2},
    {212, 3},
};
static const arc arcs_90_2[1] = {
    {78, 4},
};
static const arc arcs_90_3[1] = {
    {70, 2},
};
static const arc arcs_90_4[1] = {
    {80, 5},
};
static const arc arcs_90_5[1] = {
    {0, 5},
};
static state states_90[6] = {
    {1, arcs_90_0},
    {2, arcs_90_1},
    {1, arcs_90_2},
    {1, arcs_90_3},
    {1, arcs_90_4},
    {1, arcs_90_5},
};
static const arc arcs_91_0[3] = {
    {6, 1},
    {84, 2},
    {80, 3},
};
static const arc arcs_91_1[3] = {
    {86, 4},
    {80, 5},
    {0, 1},
};
static const arc arcs_91_2[1] = {
    {80, 6},
};
static const arc arcs_91_3[2] = {
    {86, 7},
    {0, 3},
};
static const arc arcs_91_4[2] = {
    {84, 2},
    {80, 5},
};
static const arc arcs_91_5[2] = {
    {86, 4},
    {0, 5},
};
static const arc arcs_91_6[1] = {
    {0, 6},
};
static const arc arcs_91_7[4] = {
    {6, 8},
    {84, 2},
    {80, 3},
    {0, 7},
};
static const arc arcs_91_8[3] = {
    {86, 9},
    {80, 10},
    {0, 8},
};
static const arc arcs_91_9[2] = {
    {84, 2},
    {80, 10},
};
static const arc arcs_91_10[2] = {
    {86, 9},
    {0, 10},
};
static state states_91[11] = {
    {3, arcs_91_0},
    {3, arcs_91_1},
    {1, arcs_91_2},
    {2, arcs_91_3},
    {2, arcs_91_4},
    {2, arcs_91_5},
    {1, arcs_91_6},
    {4, arcs_91_7},
    {3, arcs_91_8},
    {2, arcs_91_9},
    {2, arcs_91_10},
};
static const dfa dfas[92] = {
    {256, "single_input", 3, states_0,
     "\344\377\377\377\377\377\377\177\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {257, "file_input", 2, states_1,
     "\344\377\377\377\377\377\377\177\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {258, "eval_input", 3, states_2,
     "\240\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {259, "decorator", 7, states_3,
     "\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {260, "decorators", 2, states_4,
     "\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {261, "decorated", 3, states_5,
     "\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {262, "async_funcdef", 3, states_6,
     "\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {263, "funcdef", 9, states_7,
     "\000\000\000\005\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {264, "parameters", 4, states_8,
     "\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {265, "typedargslist", 42, states_9,
     "\100\000\000\000\000\000\000\020\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {266, "tfpdef", 4, states_10,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {267, "varargslist", 34, states_11,
     "\100\000\000\000\000\000\000\020\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {268, "vfpdef", 2, states_12,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {269, "stmt", 2, states_13,
     "\340\377\377\377\377\377\377\177\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {270, "simple_stmt", 4, states_14,
     "\340\373\277\152\322\377\205\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {271, "small_stmt", 2, states_15,
     "\340\373\277\152\322\377\205\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {272, "expr_stmt", 6, states_16,
     "\340\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {273, "annassign", 5, states_17,
     "\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {274, "testlist_star_expr", 3, states_18,
     "\340\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {275, "augassign", 2, states_19,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\374\177\000\000\000\000\000\000\000\000\000\000\000\000"},
    {276, "del_stmt", 3, states_20,
     "\000\000\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {277, "pass_stmt", 2, states_21,
     "\000\000\000\000\000\014\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {278, "flow_stmt", 2, states_22,
     "\000\000\250\010\020\160\204\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {279, "break_stmt", 2, states_23,
     "\000\000\040\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {280, "continue_stmt", 2, states_24,
     "\000\000\200\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {281, "return_stmt", 3, states_25,
     "\000\000\000\000\000\140\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {282, "yield_stmt", 2, states_26,
     "\000\000\000\000\000\000\204\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {283, "raise_stmt", 7, states_27,
     "\000\000\010\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {284, "import_stmt", 2, states_28,
     "\000\000\004\040\102\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {285, "import_name", 3, states_29,
     "\000\000\004\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {286, "import_from", 11, states_30,
     "\000\000\000\040\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {287, "import_as_name", 4, states_31,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {288, "dotted_as_name", 4, states_32,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {289, "import_as_names", 3, states_33,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {290, "dotted_as_names", 2, states_34,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {291, "dotted_name", 2, states_35,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {292, "global_stmt", 3, states_36,
     "\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {293, "nonlocal_stmt", 3, states_37,
     "\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {294, "assert_stmt", 5, states_38,
     "\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {295, "compound_stmt", 2, states_39,
     "\000\004\100\225\055\000\172\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {296, "async_stmt", 3, states_40,
     "\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {297, "if_stmt", 12, states_41,
     "\000\000\000\200\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {298, "while_stmt", 12, states_42,
     "\000\000\000\000\000\000\060\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {299, "for_stmt", 18, states_43,
     "\000\000\000\020\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {300, "try_stmt", 22, states_44,
     "\000\000\000\000\004\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {301, "with_stmt", 8, states_45,
     "\000\000\000\000\000\000\110\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {302, "with_item", 4, states_46,
     "\240\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {303, "except_clause", 7, states_47,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\000\000\000\000\000\000\000"},
    {304, "suite", 5, states_48,
     "\344\373\277\152\322\377\205\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {305, "namedexpr_test", 4, states_49,
     "\240\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {306, "test", 8, states_50,
     "\240\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {307, "test_nocond", 2, states_51,
     "\240\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {308, "lambdef", 5, states_52,
     "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {309, "lambdef_nocond", 5, states_53,
     "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {310, "or_test", 6, states_54,
     "\240\373\003\000\000\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {311, "and_test", 6, states_55,
     "\240\373\003\000\000\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {312, "not_test", 3, states_56,
     "\240\373\003\000\000\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {313, "comparison", 2, states_57,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {314, "comp_op", 6, states_58,
     "\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\014\000\000\374\007\000\000\000\000"},
    {315, "star_expr", 3, states_59,
     "\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {316, "expr", 2, states_60,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {317, "xor_expr", 2, states_61,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {318, "and_expr", 2, states_62,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {319, "shift_expr", 2, states_63,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {320, "arith_expr", 2, states_64,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {321, "term", 2, states_65,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {322, "factor", 3, states_66,
     "\240\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {323, "power", 4, states_67,
     "\040\372\003\000\000\000\000\171\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {324, "atom_expr", 3, states_68,
     "\040\372\003\000\000\000\000\171\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {325, "atom", 9, states_69,
     "\040\372\003\000\000\000\000\161\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {326, "testlist_comp", 5, states_70,
     "\340\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {327, "trailer", 7, states_71,
     "\040\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000"},
    {328, "subscriptlist", 3, states_72,
     "\240\373\003\000\200\202\000\173\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {329, "subscript", 5, states_73,
     "\240\373\003\000\200\202\000\173\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {330, "sliceop", 3, states_74,
     "\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {331, "exprlist", 3, states_75,
     "\340\373\003\000\000\000\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {332, "testlist", 3, states_76,
     "\240\373\003\000\200\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {333, "dictorsetmaker", 14, states_77,
     "\340\373\003\000\200\202\000\173\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {334, "classdef", 8, states_78,
     "\000\000\100\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {335, "arglist", 3, states_79,
     "\340\373\003\000\200\202\000\173\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {336, "argument", 4, states_80,
     "\340\373\003\000\200\202\000\173\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {337, "comp_iter", 2, states_81,
     "\000\000\000\220\011\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {338, "sync_comp_for", 8, states_82,
     "\000\000\000\020\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {339, "comp_for", 3, states_83,
     "\000\000\000\020\010\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {340, "comp_if", 4, states_84,
     "\000\000\000\200\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {341, "encoding_decl", 2, states_85,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {342, "yield_expr", 3, states_86,
     "\000\000\000\000\000\000\204\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {343, "yield_arg", 3, states_87,
     "\340\373\003\040\300\202\000\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {344, "func_body_suite", 7, states_88,
     "\344\373\277\152\322\377\205\173\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {345, "func_type_input", 3, states_89,
     "\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {346, "func_type", 6, states_90,
     "\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {347, "typelist", 11, states_91,
     "\340\373\003\000\200\202\000\173\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
};
static const label labels[213] = {
    {0, "EMPTY"},
    {256, 0},
    {4, 0},
    {295, 0},
    {270, 0},
    {7, 0},
    {16, 0},
    {14, 0},
    {15, 0},
    {52, 0},
    {49, 0},
    {1, "False"},
    {1, "Kweli"},
    {1, "None"},
    {1, "True"},
    {1, "Tupu"},
    {1, "Uongo"},
    {9, 0},
    {1, "agiza"},
    {1, "ashiria"},
    {1, "assert"},
    {1, "break"},
    {1, "class"},
    {1, "continue"},
    {1, "def"},
    {1, "del"},
    {1, "eleza"},
    {1, "endelea"},
    {1, "for"},
    {1, "from"},
    {1, "global"},
    {1, "if"},
    {1, "ikiwa"},
    {1, "import"},
    {1, "jaribu"},
    {1, "kila"},
    {1, "koma"},
    {1, "kundi"},
    {1, "kutoka"},
    {1, "lambda"},
    {1, "nonlocal"},
    {1, "not"},
    {1, "pass"},
    {1, "pita"},
    {1, "raise"},
    {1, "return"},
    {1, "rudisha"},
    {1, "sio"},
    {1, "toa"},
    {1, "try"},
    {1, "tuma"},
    {1, "ukijumuisha"},
    {1, "wakati"},
    {1, "while"},
    {1, "with"},
    {1, "yield"},
    {25, 0},
    {31, 0},
    {56, 0},
    {55, 0},
    {1, 0},
    {2, 0},
    {3, 0},
    {257, 0},
    {0, 0},
    {269, 0},
    {258, 0},
    {332, 0},
    {259, 0},
    {291, 0},
    {8, 0},
    {335, 0},
    {260, 0},
    {261, 0},
    {262, 0},
    {334, 0},
    {263, 0},
    {264, 0},
    {51, 0},
    {11, 0},
    {306, 0},
    {58, 0},
    {344, 0},
    {265, 0},
    {35, 0},
    {266, 0},
    {12, 0},
    {22, 0},
    {17, 0},
    {267, 0},
    {268, 0},
    {271, 0},
    {13, 0},
    {294, 0},
    {276, 0},
    {272, 0},
    {278, 0},
    {292, 0},
    {284, 0},
    {293, 0},
    {277, 0},
    {274, 0},
    {273, 0},
    {275, 0},
    {342, 0},
    {315, 0},
    {40, 0},
    {41, 0},
    {46, 0},
    {38, 0},
    {36, 0},
    {37, 0},
    {48, 0},
    {39, 0},
    {44, 0},
    {45, 0},
    {50, 0},
    {43, 0},
    {42, 0},
    {331, 0},
    {279, 0},
    {280, 0},
    {283, 0},
    {281, 0},
    {282, 0},
    {286, 0},
    {285, 0},
    {290, 0},
    {23, 0},
    {289, 0},
    {287, 0},
    {1, "as"},
    {1, "kama"},
    {288, 0},
    {296, 0},
    {299, 0},
    {297, 0},
    {300, 0},
    {298, 0},
    {301, 0},
    {305, 0},
    {304, 0},
    {1, "elif"},
    {1, "else"},
    {1, "isipokua"},
    {1, "lasivyo"},
    {1, "in"},
    {1, "kwenye"},
    {1, "mwishowe"},
    {303, 0},
    {1, "finally"},
    {302, 0},
    {316, 0},
    {1, "except"},
    {1, "tatizo"},
    {5, 0},
    {6, 0},
    {53, 0},
    {308, 0},
    {310, 0},
    {307, 0},
    {309, 0},
    {311, 0},
    {1, "ama"},
    {1, "or"},
    {312, 0},
    {1, "and"},
    {1, "na"},
    {313, 0},
    {314, 0},
    {28, 0},
    {20, 0},
    {29, 0},
    {27, 0},
    {21, 0},
    {30, 0},
    {1, "haiko"},
    {1, "is"},
    {1, "ni"},
    {317, 0},
    {18, 0},
    {318, 0},
    {32, 0},
    {319, 0},
    {19, 0},
    {320, 0},
    {33, 0},
    {34, 0},
    {321, 0},
    {322, 0},
    {24, 0},
    {47, 0},
    {323, 0},
    {324, 0},
    {325, 0},
    {327, 0},
    {326, 0},
    {10, 0},
    {26, 0},
    {333, 0},
    {339, 0},
    {328, 0},
    {329, 0},
    {330, 0},
    {336, 0},
    {337, 0},
    {340, 0},
    {338, 0},
    {341, 0},
    {343, 0},
    {345, 0},
    {346, 0},
    {347, 0},
};
grammar _PyParser_Grammar = {
    92,
    dfas,
    {213, labels},
    256
};
